import { InspectionRecord, Vessel } from '../types';

export const INITIAL_VESSELS: Vessel[] = [
  {
    id: 'VESSEL-001',
    name: 'KM. Samudera Makmur 08',
    registrationNumber: 'SIPI-2024-JKT-04921',
    grossTonnage: 128,
    callSign: 'YDB-8812',
    ownerName: 'PT. Bahari Sejahtera Abadi',
    agentName: 'PT. Samudera Sentosa Agent',
    homePort: 'Pelabuhan Perikanan Samudera Nizam Zachman Jakarta',
    gearType: 'Purse Seine Pelagis Besar',
    crewCapacity: 24,
    riskScore: 78,
    riskLevel: 'HIGH',
    totalInspections: 3,
    lastInspectionDate: '2025-02-14',
    lastInspectionPort: 'PPS Nizam Zachman Jakarta',
    status: 'FLAGGED',
    activeViolationsCount: 3,
    criticalViolationsCount: 2,
    lastRecommendation: 'Penundaan Penerbitan SPB sampai perbaikan PKL dan pelunasan sisa upah ABK diselesaikan.',
    createdAt: '2024-01-10T08:00:00Z',
    updatedAt: '2025-02-14T11:30:00Z'
  },
  {
    id: 'VESSEL-002',
    name: 'KM. Mina Jaya Perkasa 02',
    registrationNumber: 'SIPI-2024-BNO-01824',
    grossTonnage: 86,
    callSign: 'YDC-3301',
    ownerName: 'CV. Bintang Samudera Bali',
    agentName: 'Maju Jaya Mandiri Agen',
    homePort: 'Pelabuhan Benoa, Bali',
    gearType: 'Tuna Longline',
    crewCapacity: 18,
    riskScore: 22,
    riskLevel: 'LOW',
    totalInspections: 2,
    lastInspectionDate: '2025-02-17',
    lastInspectionPort: 'Pelabuhan Benoa, Bali',
    status: 'CLEARED',
    activeViolationsCount: 0,
    criticalViolationsCount: 0,
    lastRecommendation: 'Lolos Verifikasi Kepatuhan Ketenagakerjaan Awak Kapal. Rekomendasi SPB Disetujui.',
    createdAt: '2024-02-15T09:00:00Z',
    updatedAt: '2025-02-17T14:15:00Z'
  },
  {
    id: 'VESSEL-003',
    name: 'KM. Bintang Timur Lestari',
    registrationNumber: 'SIPI-2023-BTG-08392',
    grossTonnage: 175,
    callSign: 'YDF-9102',
    ownerName: 'PT. Pasifik Tuna Indah',
    agentName: 'PT. Kawanua Maritim Bitung',
    homePort: 'PPS Bitung, Sulawesi Utara',
    gearType: 'Pole and Line (Huhate)',
    crewCapacity: 30,
    riskScore: 48,
    riskLevel: 'MEDIUM',
    totalInspections: 4,
    lastInspectionDate: '2025-02-10',
    lastInspectionPort: 'PPS Bitung',
    status: 'ACTIVE',
    activeViolationsCount: 2,
    criticalViolationsCount: 0,
    lastRecommendation: 'Surat Peringatan: Wajib memperbarui masa berlaku 6 Buku Pelaut & mendaftarkan 4 ABK ke BPJS Ketenagakerjaan.',
    createdAt: '2023-11-20T10:00:00Z',
    updatedAt: '2025-02-10T16:00:00Z'
  },
  {
    id: 'VESSEL-004',
    name: 'KM. Arung Samudera 15',
    registrationNumber: 'SIPI-2024-BLW-00512',
    grossTonnage: 54,
    callSign: 'YDA-4491',
    ownerName: 'H. Sudirman / Usaha Nelayan Mandiri',
    agentName: 'Mandiri Maritim Belawan',
    homePort: 'PPS Belawan, Sumatera Utara',
    gearType: 'Pukat Cincin (Mini Purse Seine)',
    crewCapacity: 16,
    riskScore: 85,
    riskLevel: 'HIGH',
    totalInspections: 2,
    lastInspectionDate: '2025-02-05',
    lastInspectionPort: 'PPS Belawan',
    status: 'SUSPENDED',
    activeViolationsCount: 4,
    criticalViolationsCount: 2,
    lastRecommendation: 'Rekomendasi Penahanan Operasional: Ditemukan penahanan dokumen identitas ABK dan jam kerja melebihi batas regulasi.',
    createdAt: '2024-03-01T07:30:00Z',
    updatedAt: '2025-02-05T13:40:00Z'
  },
  {
    id: 'VESSEL-005',
    name: 'KM. Cenderawasih Bahari 07',
    registrationNumber: 'SIPI-2024-DOB-02319',
    grossTonnage: 195,
    callSign: 'YDH-1033',
    ownerName: 'PT. Arafura Fisheries Group',
    agentName: 'Arafura Mandiri Agen',
    homePort: 'Pelabuhan Dobo, Kepulauan Aru',
    gearType: 'Jaring Insang Hanyut (Drift Gillnet)',
    crewCapacity: 28,
    riskScore: 58,
    riskLevel: 'MEDIUM',
    totalInspections: 1,
    lastInspectionDate: '2025-01-28',
    lastInspectionPort: 'Pelabuhan Dobo',
    status: 'ACTIVE',
    activeViolationsCount: 2,
    criticalViolationsCount: 0,
    lastRecommendation: 'Diberi tenggat 14 hari untuk melengkapi ruang akomodasi dan kotak P3K darurat.',
    createdAt: '2024-05-12T11:00:00Z',
    updatedAt: '2025-01-28T15:20:00Z'
  },
  {
    id: 'VESSEL-006',
    name: 'KM. Maluku Prima 01',
    registrationNumber: 'SIPI-2024-AMB-09411',
    grossTonnage: 68,
    callSign: 'YDG-6623',
    ownerName: 'Koperasi Nelayan Siwalima',
    agentName: 'Siwalima Bahari Agen',
    homePort: 'PPN Tantui Ambon, Maluku',
    gearType: 'Handline Tuna Organik',
    crewCapacity: 12,
    riskScore: 15,
    riskLevel: 'LOW',
    totalInspections: 2,
    lastInspectionDate: '2025-02-18',
    lastInspectionPort: 'PPN Tantui Ambon',
    status: 'CLEARED',
    activeViolationsCount: 0,
    criticalViolationsCount: 0,
    lastRecommendation: 'Lolos Verifikasi: Tata kelola ketenagakerjaan dan K3 sangat baik.',
    createdAt: '2024-06-01T08:00:00Z',
    updatedAt: '2025-02-18T10:00:00Z'
  }
];

export const INITIAL_INSPECTIONS: InspectionRecord[] = [
  {
    id: 'INSP-202502-001',
    vesselId: 'VESSEL-001',
    vesselName: 'KM. Samudera Makmur 08',
    registrationNumber: 'SIPI-2024-JKT-04921',
    homePort: 'Pelabuhan Perikanan Samudera Nizam Zachman Jakarta',
    inspectionDate: '2025-02-14',
    inspectionPort: 'PPS Nizam Zachman Jakarta',
    leadAgency: 'Tim Pengawas Gabungan (PSDKP - Kemnaker - KSOP)',
    inspectors: 'Hendra Wijaya (PSDKP), Rahmat Santoso (Wasnaker), Dwi Putra (Pengawas Pelabuhan)',
    crewData: {
      totalCrew: 24,
      crewWithPkl: 14,
      crewWithInsurance: 12,
      crewWithSeamanBook: 20,
      crewWithBst: 18,
      hasFairWageAgreement: false,
      hasProperRestHours: false,
      hasAdequateFoodWater: true,
      hasFirstAidKits: false,
      identityHoldFlag: true
    },
    violations: [
      {
        categoryId: 'VIO-DOC-01',
        categoryName: 'DOCUMENTATION',
        title: 'ABK Tidak Memiliki Perjanjian Kerja Laut (PKL)',
        severity: 'CRITICAL',
        scoreWeight: 25,
        notes: 'Sebanyak 10 dari 24 ABK tidak memiliki PKL resmi, hanya kesepakatan lisan tanpa legalitas.'
      },
      {
        categoryId: 'VIO-FL-01',
        categoryName: 'FORCED_LABOR_INDICATOR',
        title: 'Penahanan Dokumen Identitas (KTP/Buku Pelaut)',
        severity: 'CRITICAL',
        scoreWeight: 35,
        notes: 'Buku pelaut dan KTP asli 8 orang ABK ditahan oleh pihak agen kapal dengan dalih jaminan.'
      },
      {
        categoryId: 'VIO-K3-03',
        categoryName: 'SAFETY_HEALTH',
        title: 'Perlengkapan P3K & Alat Pelindung Diri (APD) Kurang',
        severity: 'MINOR',
        scoreWeight: 6,
        notes: 'Obat-obatan di kotak P3K telah kedaluwarsa dan APD tidak memadai.'
      }
    ],
    riskEvaluation: {
      score: 78,
      riskLevel: 'HIGH',
      documentScorePenalty: 28,
      welfareScorePenalty: 35,
      violationScorePenalty: 66,
      historicalPenalty: 0,
      primaryRiskFactors: [
        '⚠️ Indikasi Penahanan Dokumen Asli Awak Kapal oleh agen (Red Flag Ketenagakerjaan).',
        'Sebagian ABK (10 orang) belum memiliki PKL sah.',
        'Kepesertaan BPJS Ketenagakerjaan / Asuransi Awak Kapal di bawah 50%.'
      ],
      recommendation: 'Rekomendasi Penundaan Penerbitan SPB (Surat Persetujuan Berlayar) & Pemanggilan Resmi Pemilik/Agen.',
      actionRequired: 'Investigasi mendalam oleh Tim Pengawas Gabungan. Wajib mengembalikan dokumen asli ABK dan menerbitkan PKL resmi.'
    },
    followUpStatus: 'PENDING',
    officialNotes: 'Berita acara telah disampaikan ke Syahbandar perikanan setempat untuk menahan SPB sementara.',
    actionDeadline: '2025-02-28',
    createdBy: 'admin@inspeksikapal.go.id',
    createdAt: '2025-02-14T11:30:00Z'
  },
  {
    id: 'INSP-202502-002',
    vesselId: 'VESSEL-002',
    vesselName: 'KM. Mina Jaya Perkasa 02',
    registrationNumber: 'SIPI-2024-BNO-01824',
    homePort: 'Pelabuhan Benoa, Bali',
    inspectionDate: '2025-02-17',
    inspectionPort: 'Pelabuhan Benoa, Bali',
    leadAgency: 'Tim Pengawas Ketenagakerjaan Pelabuhan Benoa',
    inspectors: 'I Wayan Sudiarta (Syahbandar KSOP), Ketut Arimbawa (Disnaker Bali)',
    crewData: {
      totalCrew: 18,
      crewWithPkl: 18,
      crewWithInsurance: 18,
      crewWithSeamanBook: 18,
      crewWithBst: 18,
      hasFairWageAgreement: true,
      hasProperRestHours: true,
      hasAdequateFoodWater: true,
      hasFirstAidKits: true,
      identityHoldFlag: false
    },
    violations: [],
    riskEvaluation: {
      score: 22,
      riskLevel: 'LOW',
      documentScorePenalty: 0,
      welfareScorePenalty: 0,
      violationScorePenalty: 0,
      historicalPenalty: 0,
      primaryRiskFactors: [
        'Seluruh dokumen ketenagakerjaan, PKL, dan standar K3 awak kapal terpenuhi secara baik.'
      ],
      recommendation: 'Lolos Verifikasi Kepatuhan Ketenagakerjaan Awak Kapal (Rekomendasi Layak Melaut).',
      actionRequired: 'Pencatatan rutin dalam database pengawasan dan monitoring saat sandar berikutnya.'
    },
    followUpStatus: 'RESOLVED',
    officialNotes: 'Contoh kepatuhan yang baik. 100% ABK memiliki PKL terdaftar dan jaminan BPJS aktif.',
    createdBy: 'admin@inspeksikapal.go.id',
    createdAt: '2025-02-17T14:15:00Z'
  }
];

export const INDONESIAN_PORTS = [
  'Semua Pelabuhan',
  'PPS Nizam Zachman Jakarta',
  'Pelabuhan Benoa, Bali',
  'PPS Bitung, Sulawesi Utara',
  'PPS Belawan, Sumatera Utara',
  'PPS Cilacap, Jawa Tengah',
  'PPN Tantui Ambon, Maluku',
  'Pelabuhan Dobo, Kepulauan Aru',
  'PPS Kendari, Sulawesi Tenggara',
  'PPN Brondong, Lamongan',
  'PPN Sungailiat, Bangka'
];
